version: '3'

services:
  patent-db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=patient-db-password
      - POSTGRES_USER=patient-db
      - POSTGRES_DB=patient-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  model-api:
    build: ./model-api
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
