services:
  db:
    image: postgres:16.2
    container_name: hmi-db
    environment:
      - POSTGRES_PASSWORD=patient-db-password
      - POSTGRES_USER=patient-db
      - POSTGRES_DB=patient-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  model-api:
    build: ./model-api
    container_name: hmi-model-api
    environment:
      - PORT=8080
    ports:
      - '8080:8080'

  app:
    build: ./app
    container_name: hmi-app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://patient-db:patient-db-password@db:5432/patient-db
      - MODEL_API_URL=http://model-api:8080
    ports:
      - '3000:3000'
    depends_on:
      - db
      - model-api
